let Actiontype={
    ALL_MOVIES:"ALL_MOVIES",
    SEARCH_MOVIES:"SEARCH_MOVIES",
    SELECTED_MOVIE:"SELECTED_MOVIE",
    SEARCH_MOVIES_PAGE:"SEARCH_MOVIES_PAGE",
    PAGE:"PAGE"
    }
    export default Actiontype;